MONGODB_SETTINGS = {'DB': 'skunks'}
SECRET_KEY = "KeepThisS3cr3t"

TWITTER_CONSUMER_KEY = 'VBGAfMiA6PSyUYw1nIC8WMmZh'
TWITTER_CONSUMER_SECRET = 'DLTeEp2utQ9A1vSwCM85lx5lyT9xeXqbEtinnsuCqRKvbB80Z3'
TWITTER_OAUTH_TOKEN = ''
TWITTER_OAUTH_SECRET = ''

